name: Test Python Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run pre-commit hooks
      run: |
        pip install pre-commit
        echo "SKIP=no-commit-to-branch" >> $GITHUB_ENV
        pre-commit run --all-files

    - name: Run tests with pytest
      run: |
        pip install pytest pytest-cov
        pytest
